export class Types {
    public static Authenticate = Symbol('Authenticate')
    public static DbClient = Symbol('DbClient')
    public static DiscountService = Symbol('DiscountService')
    public static Easypost = Symbol('Easypost')
    public static EasypostService = Symbol('EasypostService')
    public static EmailService = Symbol('EmailService')
    public static ErrorService = Symbol('ErrorService')
    public static ModelBuilder = Symbol('ModelBuilder')
    public static OrderService = Symbol('OrderService')
    public static ProductSearchUtils = Symbol('ProductSearchUtils')
    public static ProductService = Symbol('ProductService')
    public static StripeCustomerService = Symbol('StripeCustomerService')
    public static StripeOrderActionsService = Symbol('StripeOrderActionsService')
    public static StripeOrderService = Symbol('StripeOrderService')
    public static StripeProductService = Symbol('StripeProductService')
    public static TimerService = Symbol('TimerService')
    public static UserService = Symbol('UserService')
    public static WoocommerceMigrationService = Symbol('WoocommerceMigrationService')
    public static isAuthenticated = Symbol('isAuthenticated')
    public static isAuthorized = Symbol('isAuthorized')
}
